In [1]:
import numpy as np

# 행렬의 차원을 변경하는 방법

In [13]:
# 1차원 행렬을 생성한다.
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# 1차원 -> 2차원으로 변환
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# 2차원 -> 1차원
array3 = array2.reshape(15)
display(array3)

array4 = array2.reshape(-1)
display(array4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 통계함수

In [20]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
# 행렬이 제공하는 함수 사용하기
mean1 = array1.mean()

# numpy가 제공하는 함수 사용하기
mean2 = np.mean(array1)

print(mean1)
print(mean2)

7.0
7.0


# 로또 번호 추첨해보기

In [22]:
# 1 ~ 45 까지 가지고 있는 행렬을 생성한다.
array1 = np.arange(1, 46)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [26]:
for _ in range(10) :
    array2 = np.random.permutation(array1)
    array3 = array2[ : 6]
    array3.sort()
    display(array3)

array([11, 20, 26, 31, 38, 43])

array([ 6,  7, 10, 28, 39, 41])

array([20, 23, 24, 31, 35, 43])

array([ 4,  5, 22, 31, 37, 40])

array([ 1,  4,  5, 17, 24, 41])

array([16, 23, 33, 36, 39, 45])

array([ 6, 10, 27, 36, 39, 40])

array([ 6, 29, 32, 33, 40, 41])

array([10, 12, 20, 22, 25, 41])

array([ 8, 13, 25, 29, 35, 44])