In [3]:
x = [1, 2, 3, 4, 6]

y = 2 * x + 1



TypeError: can only concatenate list (not "int") to list

In [9]:
y = []
for i in x :
    t = 2 * i + 1
    y.append(t)
print(y)

[3, 5, 7, 9, 13]


In [7]:
y = [2 * i + 1 for i in x]
print(y)

[3, 5, 7, 9, 13]


numpy 를 사용하여 계산할 수도 있다.

In [10]:
import numpy as np

x = np.array([1,2,3,4,5,7])
y = 2 * x + 1
print(y)

[ 3  5  7  9 11 15]


# 1. 오차의 이해

In [19]:
x = np.array([1,2,3,4,5])
y = np.array([3,6,7,9,12])

w = 2
b = 1

#np.sum((w * x + b - y) ** 2) / 5
e1 = np.mean((w * x + b - y) ** 2)

w = 3
b = 0.1
e2 = np.mean((w * x + b - y) ** 2)

print(e1, e2, sep = "\n")

0.4
4.729999999999999


# 2.행렬 기초

In [27]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a)
print()

b = a * 10 + 5
print(b)
print()

c = np.array([[0,0,1],
              [1,0,0],
              [0,1,0]])
print(c)
print()

d = a * c + b + 3
print(d)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[15 25 35]
 [45 55 65]
 [75 85 95]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[18 28 41]
 [52 58 68]
 [78 96 98]]


In [28]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [7, 8]])
print(a * b)

[[ 3  8]
 [21 32]]


# 행렬 연산

In [33]:
i = np.eye(3)
print(i)
print()

b = a * 5
print(b)
print()

a = np.array([[1,2], [3,4]])

b = np.matmul(a, a)
print(b)
print()

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.matmul(i, a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

[[ 7 10]
 [15 22]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 역행렬

In [36]:
a = np.array([[1, 1], 
             [2, 1]])

inv = np.linalg.inv(a)
print(inv)
print()
print(np.matmul(a, inv))



[[-1.  1.]
 [ 2. -1.]]

[[1. 0.]
 [0. 1.]]


In [62]:
a1 = a[0][0]
a2 = a[0][1]
a3 = a[1][0]
a4 = a[1][1]

ainv = (1/(a1*a4 - a2*a3))*np.array([[a4, -a2], [-a3, a1]])
print('ainv')
print(ainv)
print()

y = np.array([[2],[4.4]])
print('y')
print(y)
print()

wb = np.matmul(ainv, y)
print('wb')
print(wb)
print()
w = wb[0][0]
b = wb[1][0]
print('w, b')
print(w,b)
print()

h = w * x + b
x = 7
print(round(h, 5))
print()

x = np.array([6,7,8,10])
h = w * x + b
print('h')
print(h)
print()

x = np.array([[7, 1],
              [8, 1],
              [9, 1]])

h = np.matmul(x, wb)
print('h')
print(h)

ainv
[[-1.  1.]
 [ 2. -1.]]

y
[[2. ]
 [4.4]]

wb
[[ 2.4]
 [-0.4]]

w, b
2.4000000000000004 -0.40000000000000036

16.4

h
[14.  16.4 18.8 23.6]

h
[[16.4]
 [18.8]
 [21.2]]


# 의사역행렬

In [69]:
a = np.array([[1, 1],
                [2,1],
                [3,1]])
y = np.array([[2],
                [4],
                [6.4]])
pinv = np.linalg.pinv(a)
print(pinv)
print()
y = np.array([[2, 4, 6.4]]).T

np.matmul(pinv, a)

W = np.matmul(pinv, y)
print(W)

[[-5.00000000e-01 -3.19189120e-16  5.00000000e-01]
 [ 1.33333333e+00  3.33333333e-01 -6.66666667e-01]]

[[ 2.2       ]
 [-0.26666667]]


In [75]:
#print(a)
mse = np.mean((np.matmul(a,W) - y) ** 2)
print(mse)



0.008888888888888925


# 택시비 추정하기

a 회차 : 1km    8000    2km   9200  3km     12000

B 회차 : 1km    5000    2km   8500  3km     11000

20km?

In [104]:
a = np.array([[1, 1],
              [2, 1],
              [3, 1]])

y_a = np.array([8000, 9200, 12000]).reshape(-1, 1)
y_b = np.array([5000, 8500, 11000]).reshape(-1, 1)
print(y_a)
print()

w_a = np.matmul(np.linalg.pinv(a), y_a)
print(w_a)
print()


w_b = np.matmul(np.linalg.pinv(a), y_b)
print(w_b)
print()

x = 20
h_a = w_a[0] * x + w_a[1]
h_b = w_b[0] * x + w_b[1]

print(h_a, h_b, sep = '\n')

x_array = np.array([[20, 1]])
np.matmul(x_array, w_a), np.matmul(x_array, w_b)

[[ 8000]
 [ 9200]
 [12000]]

[[2000.        ]
 [5733.33333333]]

[[3000.        ]
 [2166.66666667]]

[45733.33333333]
[62166.66666667]


(array([[45733.33333333]]), array([[62166.66666667]]))

a 가 더 낮은 금액으로 20km를 갈 수 있다.

# 주가 분석

In [ ]:
'''
[이자율, 실업률]   -  주가

[3.4,  1.5   .. ] 1900
[2.1,  2.5   .. ] 1700
y = w1*이자율 + w2*실업률 + b*1

[3.4 1.5 1]          1900
[2.1 2.5 1] -1       1700
[3.4 2.1 1]          1500
[1.7 2.4 1]          1000

(4x3)-1 * 4*1 
(3x4) (4x1) = 3x1
'''

In [92]:
# 이자율, 실업률
ir  = [2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75]
ur =  [5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1]
y = [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]     


#이자율 4.5%, 실업률 2.1일때 주가는?

In [116]:
b = [1 for i in range(len(ir))]
irur_array = np.array([ir,ur,b]).T
y_array = np.array(y).T

ir_ur_b = np.matmul(np.linalg.pinv(irur_array), y_array)    # ir, ur, b
x = np.array([4.5, 2.1, 1])     #ir, ur, b
np.matmul(x, ir_ur_b)

2828.026569297707

# 미분

In [117]:
a = [4, 5, 6, 10]
b = [5 - 4, 6 - 5, 10 - 6]
print(a)
print(b)

[4, 5, 6, 10]
[1, 1, 4]


In [131]:
def f(x) :
    return 4 * x + 7

x = 0
dx = 0.00000000001
(f(x + dx) - f(x)) / dx

def df(x) :
    dx = 0.000001
    return (f(x + dx) - f(x)) / dx

df(2)


4.000000000559112

In [132]:
def f2(x) :
    return 4 * x ** 2 + 20 * x - 5

def df2(x) :
    dx = 0.00001
    return((f2(x + dx) - f2(x)) / dx)

f2(5), df2(5)

(195, 60.0000399970213)

In [134]:
def df_g(f, x) :
    dx = 0.000001
    return ((f(x + dx) - f(x) )/ dx)

def fun1(x) :
    return 5 * x + 7

df_g(fun1, 6)

5.000000001587068

In [142]:
def sig(x) :
    return 1 / (1 + np.exp(-x))

df_g(sig, 0)

0.2500000000349445

# 합성함수 미분

z = (7x1 + 4x2 - 6)^2

In [ ]:
MSE =  sum  (wx + b - y)^2 
    
z = wx + b - y

MSE/dw =  2zx = 2(wx+b-y)x
MSE/db =  2z1 = 2(wx+b-y)

(wx+b-y)*x = 0
(wx+b-y) = 0