In [13]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier # 딥러닝 라이브러리
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [0,1,1,0])

In [7]:
model_logi = LogisticRegression(max_iter=1000, verbose=1)
model_logi.fit( x_data, y_data )

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [8]:
model_logi.coef_

array([[0., 0.]])

In [9]:
model_logi.intercept_

array([0.])

In [11]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [12]:
model_logi.score(x_data, y_data)

0.5

## 딥러닝 라이브러리

In [ ]:
# 

In [16]:
model_mlp = MLPClassifier(max_iter=1000) #hidden_layer_sizes=(100,)  : 2x1   : 2x100   100x1
# 2x2 2x1  
# 4x2    2x2 ==> 4x2  2x1 ==> 4x1 (0,1,1,0)

In [17]:
model_mlp.fit( x_data,y_data)

MLPClassifier(max_iter=1000)

In [18]:
model_mlp.predict( x_data)

array([0, 1, 1, 0])

In [20]:
len( model_mlp.coefs_ )

2

In [22]:
model_mlp.coefs_[0].shape # w: 2x100

(2, 100)

In [23]:
model_mlp.coefs_[1].shape # w:100x1

(100, 1)

In [30]:
len( model_mlp.intercepts_ )

2

In [32]:
model_mlp.intercepts_[0].shape

(100,)

In [33]:
model_mlp.intercepts_[1].shape

(1,)

In [ ]:
4x2  2x100  ==> 4x100   100x1  == >4x1

In [34]:
a = np.matmul( x_data, model_mlp.coefs_[0]) + model_mlp.intercepts_[0]  # 4x2 2x100
# a --> relu 
b = np.matmul( a, model_mlp.coefs_[1] ) + model_mlp.intercepts_[1]  # 4x100 100x1
# b-->sigmoid
b.shape

(4, 1)

In [36]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000) #2x200 200x1
model_mlp1.fit( x_data,y_data)

MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000)

In [37]:
model_mlp1.coefs_[0].shape

(2, 200)

In [38]:
model_mlp1.coefs_[1].shape

(200, 1)

In [39]:
model_mlp1.predict( x_data) # 4x2  2x200 ==> 4x200   200x1    ==>4x1  

array([0, 1, 1, 0])

In [40]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(200,4), max_iter=1000)
model_mlp2.fit( x_data,y_data)

MLPClassifier(hidden_layer_sizes=(200, 4), max_iter=1000)

In [41]:
model_mlp2.coefs_[0].shape

(2, 200)

In [42]:
model_mlp2.coefs_[1].shape

(200, 4)

In [43]:
model_mlp2.coefs_[2].shape

(4, 1)

In [44]:
model_mlp2.predict( x_data) # 4x2  2x200 => 4x200 200x4 ==> 4x4  4x1 => 4x1 

array([0, 1, 1, 0])