# 20210802

## nltk 설치

In [2]:
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
text = nltk.word_tokenize('It is posible cats and dogs')
text

['It', 'is', 'posible', 'cats', 'and', 'dogs']

In [4]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [5]:
nltk.pos_tag(text)

[('It', 'PRP'),
 ('is', 'VBZ'),
 ('posible', 'JJ'),
 ('cats', 'NNS'),
 ('and', 'CC'),
 ('dogs', 'NNS')]

## konlpy 설치

In [6]:
from konlpy.tag import Komoran
komoran = Komoran()

print(komoran.pos('딥러닝이 쉽나요? 어렵나요?'))
print(komoran.pos('오늘 부산 날씨는 어떤가요'))
print(komoran.pos('부산의 오늘 날씨 어때?'))

[('딥러닝이', 'NA'), ('쉽', 'VA'), ('나요', 'EF'), ('?', 'SF'), ('어렵', 'VA'), ('나요', 'EF'), ('?', 'SF')]
[('오늘', 'NNG'), ('부산', 'NNP'), ('날씨', 'NNG'), ('는', 'JX'), ('어떤', 'MM'), ('가요', 'NNP')]
[('부산', 'NNP'), ('의', 'JKG'), ('오늘', 'NNG'), ('날씨', 'NNP'), ('어떻', 'VA'), ('어', 'EF'), ('?', 'SF')]


In [7]:
from konlpy.tag import Okt
okt = Okt()

In [8]:
text = "한글 자연어 처리는 재밌다 이제부터 열심히 해야지ㅎㅎㅎ"
print(okt.morphs(text))
print(okt.pos(text))

['한글', '자연어', '처리', '는', '재밌다', '이제', '부터', '열심히', '해야지', 'ㅎㅎㅎ']
[('한글', 'Noun'), ('자연어', 'Noun'), ('처리', 'Noun'), ('는', 'Josa'), ('재밌다', 'Adjective'), ('이제', 'Noun'), ('부터', 'Josa'), ('열심히', 'Adverb'), ('해야지', 'Verb'), ('ㅎㅎㅎ', 'KoreanParticle')]


In [9]:
print(okt.morphs('열심히 할까', stem=True)) # 형태소 단위로 나눈 후 어간을 추출

['열심히', '하다']


## 뉴스 기사 분석

In [10]:
str = """
한국 여자배구대표팀이 세르비아전을 끝으로 조별리그 일정을 모두 마치고 8강전 준비에 나섰다.

세계랭킹 14위 한국은 31일 일본 도쿄 아리아케 아레나에서 열린 2020 도쿄올림픽 배구 여자 조별리그 A조 5차전에서 세르비아(10위)에 세트 스코어 0-3(18-25 17-25 15-25)으로 패했다. 지난달 31일 일본(5위)을 상대로 풀세트 접전 끝에 세트 스코어 3-2(25-19 19-25 25-22 15-25 16-14) 승리를 챙기며 8강을 확정했던 한국은 조 3위로 8강에 올랐다.

이번 대회 각 조 2~3위는 조추첨을 통해 8강전 상대가 정해진다. B조는 현재 이탈리아, 러시아 대표팀(ROC), 미국, 터키가 차례로 8강 진출을 확정했지만, 승점 차가 촘촘해 누가 상대가 될지는 아직 모른다.

일찌감치 8강을 확정해 부담이 덜했던 한국은 이날 1세트 초반 양효진의 블로킹 득점과 김연경의 공격 득점, 염혜선의 서브 득점으로 3-0으로 앞서갔다. 하지만 이후 내리 9점을 헌납해 순식간에 분위기를 뺏겼고, 1세트를 23분만에 내줬다.

2세트도 한국은 1-1에서 김연경과 김희진, 상대 범실을 묶어 4-1로 앞서가 기세를 올렸다. 이후 세르비아의 맹추격이 이어져 8-7, 1점차가 됐고 다시 연달아 4포인트를 뺏겨 8-11로 끌려가기 시작했다. 한국은 13-17에서 정지윤의 공격 득점으로 1점을 따라붙었지만 또 4포인트를 내리 내주며 흔들렸고 결국 2세트마저 헌납했다.


"""
print(str)

print(okt.morphs(str, stem=True)) # 형태소 단위로 나눈 후 어간을 추출


한국 여자배구대표팀이 세르비아전을 끝으로 조별리그 일정을 모두 마치고 8강전 준비에 나섰다.

세계랭킹 14위 한국은 31일 일본 도쿄 아리아케 아레나에서 열린 2020 도쿄올림픽 배구 여자 조별리그 A조 5차전에서 세르비아(10위)에 세트 스코어 0-3(18-25 17-25 15-25)으로 패했다. 지난달 31일 일본(5위)을 상대로 풀세트 접전 끝에 세트 스코어 3-2(25-19 19-25 25-22 15-25 16-14) 승리를 챙기며 8강을 확정했던 한국은 조 3위로 8강에 올랐다.

이번 대회 각 조 2~3위는 조추첨을 통해 8강전 상대가 정해진다. B조는 현재 이탈리아, 러시아 대표팀(ROC), 미국, 터키가 차례로 8강 진출을 확정했지만, 승점 차가 촘촘해 누가 상대가 될지는 아직 모른다.

일찌감치 8강을 확정해 부담이 덜했던 한국은 이날 1세트 초반 양효진의 블로킹 득점과 김연경의 공격 득점, 염혜선의 서브 득점으로 3-0으로 앞서갔다. 하지만 이후 내리 9점을 헌납해 순식간에 분위기를 뺏겼고, 1세트를 23분만에 내줬다.

2세트도 한국은 1-1에서 김연경과 김희진, 상대 범실을 묶어 4-1로 앞서가 기세를 올렸다. 이후 세르비아의 맹추격이 이어져 8-7, 1점차가 됐고 다시 연달아 4포인트를 뺏겨 8-11로 끌려가기 시작했다. 한국은 13-17에서 정지윤의 공격 득점으로 1점을 따라붙었지만 또 4포인트를 내리 내주며 흔들렸고 결국 2세트마저 헌납했다.



['\n', '한국', '여자배구', '대표팀', '이', '세르비아', '전', '을', '끝', '으로', '조', '별', '리그', '일정', '을', '모두', '마치', '고', '8', '강전', '준비', '에', '나서다', '.', '\n\n', '세계', '랭킹', '14', '위', '한국', '은', '31일', '일본', '도쿄', '아리아케', '아레나', '에서', '열리다', '2020', '도쿄올림픽', '배구', '여자', '조', '별', '리그', 

## 오늘의 날씨

In [11]:
result = okt.pos('오늘 부산 날씨 어때', stem = True)

# nouns = []
# for token in result :
#   if token[1] == 'Noun' :
#     nouns.append(token[0])

# print(nouns)

print(result)
print([token [0] for token in result])
nouns = [token [0] for token in result if token[1] == 'Noun']
print(nouns)

[('오늘', 'Noun'), ('부산', 'Noun'), ('날씨', 'Noun'), ('어떻다', 'Adjective')]
['오늘', '부산', '날씨', '어떻다']
['오늘', '부산', '날씨']


In [12]:
from bs4 import BeautifulSoup
import requests

city = '가산'
html = requests.get(f'https://search.naver.com/search.naver?query={city}날씨')
# html.text

In [13]:
city = ''
for token in nouns  :
    if token == '오늘'  :
       day = token 
    elif token == '날씨' :
        intent = '날씨'
    else :
        city = token
print(city)

부산


In [14]:
soup = BeautifulSoup(html.text, 'html.parser')
cast = soup.select_one('p.cast_txt')
temps = soup.select_one('span.todaytemp')
print(cast.text)
print(temps.text)

맑음, 어제보다 3˚ 높아요
29


In [15]:
def getWeather(str) :
    result = okt.pos(str, stem = True)
    nouns = [token [0] for token in result if token[1] == 'Noun']
    city = ''
    for token in nouns  :
        if token == '오늘'  :
           day = token 
        elif token == '날씨' :
            intent = '날씨'
        else :
            city = token
    print(city)        
    
    html = requests.get(f'https://search.naver.com/search.naver?query={city}날씨')
    
    soup = BeautifulSoup(html.text, 'html.parser')
    cast = soup.select_one('p.cast_txt')
    temps = soup.select_one('span.todaytemp')
    return f'{city} 날씨 : {cast.text}, 온도 : {temps.text}'
    
getWeather("오늘 가산 날씨 어때?")

가산


'가산 날씨 : 맑음, 어제보다 3˚ 높아요, 온도 : 29'

In [16]:
okt.pos('부산의 어제 날씨 어때', stem=True)

[('부산', 'Noun'),
 ('의', 'Josa'),
 ('어제', 'Noun'),
 ('날씨', 'Noun'),
 ('어떻다', 'Adjective')]

## 결측치 처리

In [19]:
import pandas as pd
df = pd.read_csv('data/class2.csv')
df

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I    NaN    NaN    NaN
3           3  mdb003      C  CIRC      B    NaN    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [20]:
df.isnull().sum()
df = df.dropna(how = 'all')
print(df)

   Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I    NaN    NaN    NaN
3           3  mdb003      C  CIRC      B    NaN    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0


In [21]:
df.dropna()

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [22]:
df2 = df.fillna(0)
df2

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I    0.0    0.0    0.0
3           3  mdb003      C  CIRC      B    0.0    0.0    0.0
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [23]:
df['x'].fillna(df['x'].mean(), inplace=True)
print(df)

   Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I  500.0    NaN    NaN
3           3  mdb003      C  CIRC      B  500.0    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0


## 기계학습을 이용한 결측치 처리

In [24]:
from sklearn import linear_model

### x만 가지고 y를 추정하는 방법

In [25]:
df1 = df.dropna()
X = df1['x'].values.reshape(-1, 1)
y = df1['y'].values.reshape(-1, 1)

print(X, y)
print(X.shape, y.shape)

[[535.]
 [433.]
 [488.]
 [544.]] [[475.]
 [268.]
 [145.]
 [178.]]
(4, 1) (4, 1)


In [26]:
model_lr = linear_model.LinearRegression()
model_lr.fit(X, y)

LinearRegression()

In [27]:
model_lr.coef_ # w

array([[0.6108545]])

In [28]:
model_lr.intercept_ # b

array([-38.92725173])

In [29]:
model_lr.predict(X)

array([[287.87990762],
       [225.57274827],
       [259.16974596],
       [293.37759815]])

### x와 r을 가지고 y를 추정하는 방법

In [30]:
df1 = df.dropna()
X = df1[['x', 'r']].values.reshape(-1, 2)
y = df1['y'].values.reshape(-1, 1)

print(X, y)
print(X.shape, y.shape)

model_lr = linear_model.LinearRegression()
model_lr.fit(X, y)

print(model_lr.coef_) # w1, w2

print(model_lr.intercept_) # b

model_lr.predict(X)

[[535. 192.]
 [433.  58.]
 [488.  29.]
 [544.  26.]] [[475.]
 [268.]
 [145.]
 [178.]]
(4, 2) (4, 1)
[[-0.27851257  1.90956666]]
[260.15182794]


array([[477.7844012 ],
       [250.31075073],
       [179.61512605],
       [158.28972203]])

## 문장 및 단어 구분

In [31]:
from nltk import sent_tokenize
text_sample = 'Natural Language Processing, or NLP, is the process of extracting the meaning, or intent, behind human language. In the field of Conversational artificial intelligence (AI), NLP allows machines and applications to understand the intent of human language inputs, and then generate appropriate responses, resulting in a natural conversation flow.'
tokenized_sentences = sent_tokenize(text_sample)
print(tokenized_sentences)
print(tokenized_sentences[0])
print(tokenized_sentences[1])

['Natural Language Processing, or NLP, is the process of extracting the meaning, or intent, behind human language.', 'In the field of Conversational artificial intelligence (AI), NLP allows machines and applications to understand the intent of human language inputs, and then generate appropriate responses, resulting in a natural conversation flow.']
Natural Language Processing, or NLP, is the process of extracting the meaning, or intent, behind human language.
In the field of Conversational artificial intelligence (AI), NLP allows machines and applications to understand the intent of human language inputs, and then generate appropriate responses, resulting in a natural conversation flow.


In [32]:
str = """

한국 여자배구대표팀이 세르비아전을 끝으로 조별리그 일정을 모두 마치고 8강전 준비에 나섰다.

세계랭킹 14위 한국은 31일 일본 도쿄 아리아케 아레나에서 열린 2020 도쿄올림픽 배구 여자 조별리그 A조 5차전에서 세르비아(10위)에 세트 스코어 0-3(18-25 17-25 15-25)으로 패했다. 지난달 31일 일본(5위)을 상대로 풀세트 접전 끝에 세트 스코어 3-2(25-19 19-25 25-22 15-25 16-14) 승리를 챙기며 8강을 확정했던 한국은 조 3위로 8강에 올랐다.

이번 대회 각 조 2~3위는 조추첨을 통해 8강전 상대가 정해진다. B조는 현재 이탈리아, 러시아 대표팀(ROC), 미국, 터키가 차례로 8강 진출을 확정했지만, 승점 차가 촘촘해 누가 상대가 될지는 아직 모른다.

일찌감치 8강을 확정해 부담이 덜했던 한국은 이날 1세트 초반 양효진의 블로킹 득점과 김연경의 공격 득점, 염혜선의 서브 득점으로 3-0으로 앞서갔다. 하지만 이후 내리 9점을 헌납해 순식간에 분위기를 뺏겼고, 1세트를 23분만에 내줬다.

2세트도 한국은 1-1에서 김연경과 김희진, 상대 범실을 묶어 4-1로 앞서가 기세를 올렸다. 이후 세르비아의 맹추격이 이어져 8-7, 1점차가 됐고 다시 연달아 4포인트를 뺏겨 8-11로 끌려가기 시작했다. 한국은 13-17에서 정지윤의 공격 득점으로 1점을 따라붙었지만 또 4포인트를 내리 내주며 흔들렸고 결국 2세트마저 헌납했다.


"""

kors = sent_tokenize(str)
print(kors)
for s in kors :
    print('-> ', s)
    
kors = [s.replace('\n', '') for s in sent_tokenize(str)]

print(kors)

['\n\n한국 여자배구대표팀이 세르비아전을 끝으로 조별리그 일정을 모두 마치고 8강전 준비에 나섰다.', '세계랭킹 14위 한국은 31일 일본 도쿄 아리아케 아레나에서 열린 2020 도쿄올림픽 배구 여자 조별리그 A조 5차전에서 세르비아(10위)에 세트 스코어 0-3(18-25 17-25 15-25)으로 패했다.', '지난달 31일 일본(5위)을 상대로 풀세트 접전 끝에 세트 스코어 3-2(25-19 19-25 25-22 15-25 16-14) 승리를 챙기며 8강을 확정했던 한국은 조 3위로 8강에 올랐다.', '이번 대회 각 조 2~3위는 조추첨을 통해 8강전 상대가 정해진다.', 'B조는 현재 이탈리아, 러시아 대표팀(ROC), 미국, 터키가 차례로 8강 진출을 확정했지만, 승점 차가 촘촘해 누가 상대가 될지는 아직 모른다.', '일찌감치 8강을 확정해 부담이 덜했던 한국은 이날 1세트 초반 양효진의 블로킹 득점과 김연경의 공격 득점, 염혜선의 서브 득점으로 3-0으로 앞서갔다.', '하지만 이후 내리 9점을 헌납해 순식간에 분위기를 뺏겼고, 1세트를 23분만에 내줬다.', '2세트도 한국은 1-1에서 김연경과 김희진, 상대 범실을 묶어 4-1로 앞서가 기세를 올렸다.', '이후 세르비아의 맹추격이 이어져 8-7, 1점차가 됐고 다시 연달아 4포인트를 뺏겨 8-11로 끌려가기 시작했다.', '한국은 13-17에서 정지윤의 공격 득점으로 1점을 따라붙었지만 또 4포인트를 내리 내주며 흔들렸고 결국 2세트마저 헌납했다.']
->  

한국 여자배구대표팀이 세르비아전을 끝으로 조별리그 일정을 모두 마치고 8강전 준비에 나섰다.
->  세계랭킹 14위 한국은 31일 일본 도쿄 아리아케 아레나에서 열린 2020 도쿄올림픽 배구 여자 조별리그 A조 5차전에서 세르비아(10위)에 세트 스코어 0-3(18-25 17-25 15-25)으로 패했다.
->  지난달 31일 일본(5위)을 상대로 풀세트 접전 끝에 세트 스코어 3-2(25-19 19-25 25-22 15-25 

In [33]:
from nltk import word_tokenize
sentence = ' This book is for deep learning learners'
words = word_tokenize(sentence)
print(words)

result = [ word_tokenize(s) for s in sent_tokenize(str) ]
print(result)

['This', 'book', 'is', 'for', 'deep', 'learning', 'learners']
[['한국', '여자배구대표팀이', '세르비아전을', '끝으로', '조별리그', '일정을', '모두', '마치고', '8강전', '준비에', '나섰다', '.'], ['세계랭킹', '14위', '한국은', '31일', '일본', '도쿄', '아리아케', '아레나에서', '열린', '2020', '도쿄올림픽', '배구', '여자', '조별리그', 'A조', '5차전에서', '세르비아', '(', '10위', ')', '에', '세트', '스코어', '0-3', '(', '18-25', '17-25', '15-25', ')', '으로', '패했다', '.'], ['지난달', '31일', '일본', '(', '5위', ')', '을', '상대로', '풀세트', '접전', '끝에', '세트', '스코어', '3-2', '(', '25-19', '19-25', '25-22', '15-25', '16-14', ')', '승리를', '챙기며', '8강을', '확정했던', '한국은', '조', '3위로', '8강에', '올랐다', '.'], ['이번', '대회', '각', '조', '2~3위는', '조추첨을', '통해', '8강전', '상대가', '정해진다', '.'], ['B조는', '현재', '이탈리아', ',', '러시아', '대표팀', '(', 'ROC', ')', ',', '미국', ',', '터키가', '차례로', '8강', '진출을', '확정했지만', ',', '승점', '차가', '촘촘해', '누가', '상대가', '될지는', '아직', '모른다', '.'], ['일찌감치', '8강을', '확정해', '부담이', '덜했던', '한국은', '이날', '1세트', '초반', '양효진의', '블로킹', '득점과', '김연경의', '공격', '득점', ',', '염혜선의', '서브', '득점으로', '3-0으로', '앞서갔다', '.'], ['하지만', '이

In [34]:
sent_tokenize("it's  ! hello name.. dfnlk...test")

["it's  !", 'hello name.. dfnlk...test']

In [35]:
word_tokenize("it's test")

['it', "'s", 'test']

In [36]:
from nltk.tokenize import WordPunctTokenizer  
sentence = "it’s nothing that you don’t already know except most people aren’t aware of how their inner world works."
words = WordPunctTokenizer().tokenize(sentence)
print(words)

['it', '’', 's', 'nothing', 'that', 'you', 'don', '’', 't', 'already', 'know', 'except', 'most', 'people', 'aren', '’', 't', 'aware', 'of', 'how', 'their', 'inner', 'world', 'works', '.']


## 한글 문서 형태소 분리

In [37]:
import csv

f = open('data/ratings_train.txt', 'r', encoding = 'utf-8')
rdr = csv.reader(f, delimiter = '\t')
rdw = list(rdr)
f.close()

In [38]:
rdw

[['id', 'document', 'label'],
 ['9976970', '아 더빙.. 진짜 짜증나네요 목소리', '0'],
 ['3819312', '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나', '1'],
 ['10265843', '너무재밓었다그래서보는것을추천한다', '0'],
 ['9045019', '교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정', '0'],
 ['6483659',
  '사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다',
  '1'],
 ['5403919', '막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.', '0'],
 ['7797314', '원작의 긴장감을 제대로 살려내지못했다.', '0'],
 ['9443947',
  '별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네',
  '0'],
 ['7156791', '액션이 없는데도 재미 있는 몇안되는 영화', '1'],
 ['5912145', '왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?', '1'],
 ['9008700', '걍인피니트가짱이다.진짜짱이다♥', '1'],
 ['10217543', '볼때마다 눈물나서 죽겠다90년대의 향수자극!!허진호는 감성절제멜로의 달인이다~', '1'],
 ['5957425', '울면서 손들고 횡단보도 건널때 뛰쳐나올뻔 이범수 연기 드럽게못해', '0'],
 ['8628627', '담백하고 깔끔해서 좋다. 신문기사로만 보다 보면 자꾸 잊어버린다. 그들도 사람이었다는 것을.', '1'],
 ['9864035', '취향은 존중한다지만 진짜 내생에 극장에서 본 영화중 가장 노잼 노감동임 스토리도 어거지고 감동도 어거지', '0'],
 ['6852435', 'ㄱ냥 매번 긴장되고 재밋음ㅠㅠ', '1

In [39]:
rdw[0]

['id', 'document', 'label']

In [40]:
rdw[1]

['9976970', '아 더빙.. 진짜 짜증나네요 목소리', '0']

In [41]:
twitter = Okt()

result = []
for line in rdw :
    malist = twitter.pos( line[1], norm = True, stem = True )
    r = []
    for word in malist :
        if not word[1] in ['Josa', 'Eomi', 'Punctuation'] :
            r.append(word[0])
    rl = (" ".join(r)).strip()
    result.append(rl)
    print(rl)

document
아 더빙 진짜 짜증나다 목소리
흠 포스터 보고 초딩 영화 줄 오버 연기 가볍다 않다
너 무재 밓었 다그 래서 보다 추천 다
교도소 이야기 구먼 솔직하다 재미 없다 평점 조정
사이 몬페 그 의 익살스럽다 연기 돋보이다 영화 스파이더맨 늙다 보이다 하다 커스틴 던스트 너무나도 이쁘다 보이다
막 걸음 마 떼다 3 세 초등학교 1 학년 생인 8 살다 영화 ㅋㅋㅋ 별 반개 아깝다 움
원작 긴장감 제대로 살리다 하다
별 반개 아깝다 욕 나오다 이응경 길용우 연 기 생활 몇 년 정말 발 해도 그것 낫다 납치 감금 반복 반복 이 드라마 가족 없다 연기 못 하다 사람 모 엿 네
액션 없다 재미 있다 몇 안되다 영화
왜 이렇게 평점 낮다 꽤 볼 한 데 헐리우드 식 화려하다 너무 길들이다 있다
걍 인피니트 짱 진짜 짱 ♥
볼때 눈물나다 죽다 90년 대의 향수 자극 허진호 감성 절제 멜로 달인
울면 손 들 횡단보도 건너다 때 뛰다 치다 올 뻔 이범수 연기 드럽다 못 하다
담백하다 깔끔하다 좋다 신 문 기 사 로만 보다 보다 자꾸 잊어버리다 그 들 사람 이다 것
취향 존중 한 다지 진짜 내생 극장 보다 영화 중 가장 노잼 노 감동 임 스토리 어거지 감동 어거지
ㄱ 냥 매번 긴장 되다 재밌다 ㅠㅠ
차다 사람 들 웃기다 바스코 이기 락스 코 끄다 바비 이기 아이돌 깔다 그냥 끄다 안달 것 보이다
굿바이 레닌 표절 것 이해 하다 왜 뒤 갈수록 재미 없어지다
이 것 정말 깨알 캐스팅 질퍽 하 않다 산뜻하다 내 용구성 자다 버무러진 깨알 일드 ♥
약탈 자 위 변명 이르다 저 놈 들 착하다 놈 들 절대 아니다 걸
나름 심오하다 뜻 있다 듯 그냥 학생 선생 놀다 영화 절대 아니다
보다 웃다 않다 건 불가능하다
재미없다 지루하다 같다 음식 영화 도 바베트 만찬 넘다 차이나다 바베트 만찬 이야기 있다 음식 보다 재미 있다 이 것 볼 없다 음식 별로 안 나오다 핀란드 풍경 구 경 할랫 늘다 그것 별로 안 나오다 ㅡㅡ
절대 평범하다 영화 아니다 수작 는걸 말씀드리다
주제 좋다 중반 지루

KeyboardInterrupt: 

In [42]:
%%time
twitter = Okt()

result = []
for line in rdw :
    malist = twitter.pos( line[1], norm = True, stem = True )
    r = []
    for word in malist :
        if not word[1] in ['Josa', 'Eomi', 'Punctuation'] :
            r.append(word[0])
    rl = (" ".join(r)).strip()
    result.append(rl)
    #print(rl)

KeyboardInterrupt: 

In [43]:
with open('NaverMovie.nlp', 'w', encoding = 'utf-8') as fp :
    fp.write('\n'.join(result))

## 불용어 처리

In [44]:
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import word_tokenize

sample_text = "One of the first things that we ask ourselves is what are the pros and cons of any task we perform."
text_tokens = word_tokenize(sample_text)

tokens_without_sw = [word for word in text_tokens if not word in stopwords.words('english')]
print("불용어 제거 미적용:", text_tokens, '\n')
print("불용어 제거 적용:",tokens_without_sw)

불용어 제거 미적용: ['One', 'of', 'the', 'first', 'things', 'that', 'we', 'ask', 'ourselves', 'is', 'what', 'are', 'the', 'pros', 'and', 'cons', 'of', 'any', 'task', 'we', 'perform', '.'] 

불용어 제거 적용: ['One', 'first', 'things', 'ask', 'pros', 'cons', 'task', 'perform', '.']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [45]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [46]:
stopwords.words('')

OSError: No such file or directory: 'C:\\Users\\medici\\AppData\\Roaming\\nltk_data\\corpora\\stopwords\\korean'

## 어간 추출

In [70]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

print(stemmer.stem('obesses'),stemmer.stem('obssesed'))
print(stemmer.stem('standardizes'),stemmer.stem('standardization'))
print(stemmer.stem('national'), stemmer.stem('nation'))
print(stemmer.stem('absentness'), stemmer.stem('absently'))
print(stemmer.stem('tribalical'), stemmer.stem('tribalicalized'))

obess obsses
standard standard
nation nation
absent absent
tribal tribalic


In [71]:
import nltk
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

print(stemmer.stem('obsesses'),stemmer.stem('obsessed'))
print(lemma.lemmatize('standardizes'),lemma.lemmatize('standardization'))
print(lemma.lemmatize('national'), lemma.lemmatize('nation'))
print(lemma.lemmatize('absentness'), lemma.lemmatize('absently'))
print(lemma.lemmatize('tribalical'), lemma.lemmatize('tribalicalized'))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


obsess obsess
standardizes standardization
national nation
absentness absently
tribalical tribalicalized


In [72]:
print(lemma.lemmatize('obsesses', 'v'),lemma.lemmatize('obsessed','a'))
print(lemma.lemmatize('standardizes','v'),lemma.lemmatize('standardization','n'))
print(lemma.lemmatize('national','a'), lemma.lemmatize('nation','n'))
print(lemma.lemmatize('absentness','n'), lemma.lemmatize('absently','r'))
print(lemma.lemmatize('tribalical','a'), lemma.lemmatize('tribalicalized','v'))

obsess obsessed
standardize standardization
national nation
absentness absently
tribalical tribalicalized


In [76]:
twitter.pos('아버지가방에들어가시다', norm = True, stem = True)

[('아버지', 'Noun'), ('가방', 'Noun'), ('에', 'Josa'), ('들어가다', 'Verb')]

1 ) intent 인식

        -> 날씨 물어보는 의도
        
    isIntent('오늘 부산 날씨 어때?', ['날씨', '어떻다'])    # True
    
    isIntent('짜장면 가격은', ['가격'])    # True   



In [109]:
# 내가 한거
def isIntent(text, lst) :
    result = okt.pos(text, stem = True)
    ans = 0
    for token in result :
        if token[0] in lst :
            ans += 1
        else :
            pass
    if ans == len(lst) :
        return True
    else : 
        return False
    
print(isIntent('오늘 부산 날씨 어때?', ['날씨', '어떻다']))
print(isIntent('짜장면 가격이 얼마야', ['가격', '얼마']))
    

True
True


In [111]:
# 모범답안 1
def isIntent(sentence, keywords) :    
    sentence =  [word[0] for  word    in twitter.pos(sentence, norm=True, stem=True)  ]
    nouns = [ token[0]  for token in result if token[1] == 'Noun' ]
    return True

print(isIntent('오늘 부산 날씨 어때?', ['날씨', '어떻다']))   
print(isIntent('짜장면 가격이 얼마야', ['가격', '얼마']))

True
True


In [108]:
# 모번답안 2
def isIntent(sentence, words) :  
    sentence =  [word[0] for  word    in twitter.pos(sentence, norm=True, stem=True)  ]
    print(sentence)
    return len([s for s in sentence  if  s in words  ]) == len(words)

isIntent('오늘 부산 날씨는 어때?', ['날씨', '어떻다'])  

['오늘', '부산', '날씨', '는', '어떻다', '?']


True

2) 한글 불용어 처리

stopwords = # 파일에서 읽기

getWord(" 그러니까 오늘 부산 어때?", stopwords)

3) 기계학습을 이용한 결측치 처리

## summary

In [48]:
import nltk
import pandas as pd
from konlpy.tag import Okt
from sklearn import linear_model

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\medici\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [49]:
twitter = Okt()

### 1) intent 인식
- isIntent("오늘 부산 날씨 어때?", ['날씨', '어떻다']) # True
- isIntent("오늘 부산 날씨 알려줘", ['날씨' '알다']) # True
- isIntent("짜장면 가격이 얼마야", ['가격', '얼마']) #True
- intent 인식 엔진

if isIntent(query, ['날씨', '어떻다'] ) : print("날씨 intent")

elif isIntent(query, ['가격', '얼마'] ) : print("가격 intent")

In [50]:
def isIntent(sentence, words) :     
    sentence =  [word[0] for  word in twitter.pos(sentence, norm=True, stem=True)  ]
    #print(sentence)
    return len([s for s in sentence  if  s in words  ]) == len(words)

isIntent('오늘 부산 날씨는 어때?', ['?', '어떻다'])  

True


# 2) 한글 불용어 처리
- getWord("아이쿠 그래서 오늘 우리 그러니까 부산 어때?", stopwords)   # 오늘 부산 어때

In [52]:
stopwords = "아 휴 아이구 아이쿠 아이고 어 나 우리 저희 따라 의해 을 를 에 의 가 으로 로 에게 뿐이다 의거하여 근거하여 입각하여 기준으로 예하면 예를 들면 예를 들자면 저 소인 소생 저희 지말고 하지마 하지마라 다른 물론 또한 그리고 비길수 없다 해서는 안된다 뿐만 아니라 만이 아니다 만은 아니다 막론하고 관계없이 그치지 않다 그러나 그런데 하지만 든간에 논하지 않다 따지지 않다 설사 비록 더라도 아니면 만 못하다 하는 편이 낫다 불문하고 향하여 향해서 향하다 쪽으로 틈타 이용하여 타다 오르다 제외하고 이 외에 이 밖에 하여야 비로소 한다면 몰라도 외에도 이곳 여기 부터 기점으로 따라서 할 생각이다 하려고하다 이리하여 그리하여 그렇게 함으로써 하지만 일때 할때 앞에서 중에서 보는데서 으로써 로써 까지 해야한다 일것이다 반드시 할줄알다 할수있다 할수있어 임에 틀림없다 한다면 등 등등 제 겨우 단지 다만 할뿐 딩동 댕그 대해서 대하여 대하면 훨씬 얼마나 얼마만큼 얼마큼 남짓 여 얼마간 약간 다소 좀 조금 다수 몇 얼마 지만 하물며 또한 그러나 그렇지만 하지만 이외에도 대해 말하자면 뿐이다 다음에 반대로 반대로 말하자면 이와 반대로 바꾸어서 말하면 바꾸어서 한다면 만약 그렇지않으면 까악 툭 딱 삐걱거리다 보드득 비걱거리다 꽈당 응당 해야한다 에 가서 각 각각 여러분 각종 각자 제각기 하도록하다 와 과 그러므로 그래서 고로 한 까닭에 하기 때문에 거니와 이지만 대하여 관하여 관한 과연 실로 아니나다를가 생각한대로 진짜로 한적이있다 하곤하였다 하 하하 허허 아하 거바 와 오 왜 어째서 무엇때문에 어찌 하겠는가 무슨 어디 어느곳 더군다나 하물며 더욱이는 어느때 언제 야 이봐 어이 여보시오 흐흐 흥 휴 헉헉 헐떡헐떡 영차 여차 어기여차 끙끙 아야 앗 아야 콸콸 졸졸 좍좍 뚝뚝 주룩주룩 솨 우르르 그래도 또 그리고 바꾸어말하면 바꾸어말하자면 혹은 혹시 답다 및 그에 따르는 때가 되어 즉 지든지 설령 가령 하더라도 할지라도 일지라도 지든지 몇 거의 하마터면 인젠 이젠 된바에야 된이상 만큼 어찌됏든 그위에 게다가 점에서 보아 비추어 보아 고려하면 하게될것이다 일것이다 비교적 좀 보다더 비하면 시키다 하게하다 할만하다 의해서 연이서 이어서 잇따라 뒤따라 뒤이어 결국 의지하여 기대여 통하여 자마자 더욱더 불구하고 얼마든지 마음대로 주저하지 않고 곧 즉시 바로 당장 하자마자 밖에 안된다 하면된다 그래 그렇지 요컨대 다시 말하자면 바꿔 말하면 즉 구체적으로 말하자면 시작하여 시초에 이상 허 헉 허걱 바와같이 해도좋다 해도된다 게다가 더구나 하물며 와르르 팍 퍽 펄렁 동안 이래 하고있었다 이었다 에서 로부터 까지 예하면 했어요 해요 함께 같이 더불어 마저 마저도 양자 모두 습니다 가까스로 하려고하다 즈음하여 다른 다른 방면으로 해봐요 습니까 했어요 말할것도 없고 무릎쓰고 개의치않고 하는것만 못하다 하는것이 낫다 매 매번 들 모 어느것 어느 로써 갖고말하자면 어디 어느쪽 어느것 어느해 어느 년도 라 해도 언젠가 어떤것 어느것 저기 저쪽 저것 그때 그럼 그러면 요만한걸 그래 그때 저것만큼 그저 이르기까지 할 줄 안다 할 힘이 있다 너 너희 당신 어찌 설마 차라리 할지언정 할지라도 할망정 할지언정 구토하다 게우다 토하다 메쓰겁다 옆사람 퉤 쳇 의거하여 근거하여 의해 따라 힘입어 그 다음 버금 두번째로 기타 첫번째로 나머지는 그중에서 견지에서 형식으로 쓰여 입장에서 위해서 단지 의해되다 하도록시키다 뿐만아니라 반대로 전후 전자 앞의것 잠시 잠깐 하면서 그렇지만 다음에 그러한즉 그런즉 남들 아무거나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 어떻게 만약 만일 위에서 서술한바와같이 인 듯하다 하지 않는다면 만약에 무엇 무슨 어느 어떤 아래윗 조차 한데 그럼에도 불구하고 여전히 심지어 까지도 조차도 하지 않도록 않기 위하여 때 시각 무렵 시간 동안 어때 어떠한 하여금 네 예 우선 누구 누가 알겠는가 아무도 줄은모른다 줄은 몰랏다 하는 김에 겸사겸사 하는바 그런 까닭에 한 이유는 그러니 그러니까 때문에 그 너희 그들 너희들 타인 것 것들 너 위하여 공동으로 동시에 하기 위하여 어찌하여 무엇때문에 붕붕 윙윙 나 우리 엉엉 휘익 윙윙 오호 아하 어쨋든 만 못하다 하기보다는 차라리 하는 편이 낫다 흐흐 놀라다 상대적으로 말하자면 마치 아니라면 쉿 그렇지 않으면 그렇지 않다면 안 그러면 아니었다면 하든지 아니면 이라면 좋아 알았어 하는것도 그만이다 어쩔수 없다 하나 일 일반적으로 일단 한켠으로는 오자마자 이렇게되면 이와같다면 전부 한마디 한항목 근거로 하기에 아울러 하지 않도록 않기 위해서 이르기까지 이 되다 로 인하여 까닭으로 이유만으로 이로 인하여 그래서 이 때문에 그러므로 그런 까닭에 알 수 있다 결론을 낼 수 있다 으로 인하여 있다 어떤것 관계가 있다 관련이 있다 연관되다 어떤것들 에 대해 이리하여 그리하여 여부 하기보다는 하느니 하면 할수록 운운 이러이러하다 하구나 하도다 다시말하면 다음으로 에 있다 에 달려 있다 우리 우리들 오히려 하기는한데 어떻게 어떻해 어찌됏어 어때 어째서 본대로 자 이 이쪽 여기 이것 이번 이렇게말하자면 이런 이러한 이와 같은 요만큼 요만한 것 얼마 안 되는 것 이만큼 이 정도의 이렇게 많은 것 이와 같다 이때 이렇구나 것과 같이 끼익 삐걱 따위 와 같은 사람들 부류의 사람들 왜냐하면 중의하나 오직 오로지 에 한하다 하기만 하면 도착하다 까지 미치다 도달하다 정도에 이르다 할 지경이다 결과에 이르다 관해서는 여러분 하고 있다 한 후 혼자 자기 자기집 자신 우에 종합한것과같이 총적으로 보면 총적으로 말하면 총적으로 대로 하다 으로서 참 그만이다 할 따름이다 쿵 탕탕 쾅쾅 둥둥 봐 봐라 아이야 아니 와아 응 아이 참나 년 월 일 령 영 일 이 삼 사 오 육 륙 칠 팔 구 이천육 이천칠 이천팔 이천구 하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 령 영 이 있 하 것 들 그 되 수 이 보 않 없 나 사람 주 아니 등 같 우리 때 년 가 한 지 대하 오 말 일 그렇 위하 때문 그것 두 말하 알 그러나 받 못하 일 그런 또 문제 더 사회 많 그리고 좋 크 따르 중 나오 가지 씨 시키 만들 지금 생각하 그러 속 하나 집 살 모르 적 월 데 자신 안 어떤 내 내 경우 명 생각 시간 그녀 다시 이런 앞 보이 번 나 다른 어떻 여자 개 전 들 사실 이렇 점 싶 말 정도 좀 원 잘 통하 놓" 
stopwords = stopwords.split()
stopwords

['아',
 '휴',
 '아이구',
 '아이쿠',
 '아이고',
 '어',
 '나',
 '우리',
 '저희',
 '따라',
 '의해',
 '을',
 '를',
 '에',
 '의',
 '가',
 '으로',
 '로',
 '에게',
 '뿐이다',
 '의거하여',
 '근거하여',
 '입각하여',
 '기준으로',
 '예하면',
 '예를',
 '들면',
 '예를',
 '들자면',
 '저',
 '소인',
 '소생',
 '저희',
 '지말고',
 '하지마',
 '하지마라',
 '다른',
 '물론',
 '또한',
 '그리고',
 '비길수',
 '없다',
 '해서는',
 '안된다',
 '뿐만',
 '아니라',
 '만이',
 '아니다',
 '만은',
 '아니다',
 '막론하고',
 '관계없이',
 '그치지',
 '않다',
 '그러나',
 '그런데',
 '하지만',
 '든간에',
 '논하지',
 '않다',
 '따지지',
 '않다',
 '설사',
 '비록',
 '더라도',
 '아니면',
 '만',
 '못하다',
 '하는',
 '편이',
 '낫다',
 '불문하고',
 '향하여',
 '향해서',
 '향하다',
 '쪽으로',
 '틈타',
 '이용하여',
 '타다',
 '오르다',
 '제외하고',
 '이',
 '외에',
 '이',
 '밖에',
 '하여야',
 '비로소',
 '한다면',
 '몰라도',
 '외에도',
 '이곳',
 '여기',
 '부터',
 '기점으로',
 '따라서',
 '할',
 '생각이다',
 '하려고하다',
 '이리하여',
 '그리하여',
 '그렇게',
 '함으로써',
 '하지만',
 '일때',
 '할때',
 '앞에서',
 '중에서',
 '보는데서',
 '으로써',
 '로써',
 '까지',
 '해야한다',
 '일것이다',
 '반드시',
 '할줄알다',
 '할수있다',
 '할수있어',
 '임에',
 '틀림없다',
 '한다면',
 '등',
 '등등',
 '제',
 '겨우',
 '단지',
 '다만',
 '할뿐',
 '딩동',
 '댕그',
 '대해서',
 '대하여',
 '대하면',


In [53]:
sentence = "아이쿠 그래서 오늘 우리 그러니까 부산 어때?"
sentence = sentence.split()

#print(sentence)

result = [token  for  token  in  sentence if not token in stopwords]
result = ' '.join(result)
print(result)

오늘 부산 어때?


In [58]:
def getWord(sentence, stopwords) :
    sentence = sentence.split()
    result = [token  for  token  in  sentence if not token in stopwords]
    return ' '.join(result)

getWord('아이쿠 그래서 오늘 우리 그러니까 부산 어때?', stopwords)

'오늘 부산 어때?'

## 3) 기계학습을 이용한 결측치 처리

In [69]:
df = pd.read_csv('data/class2.csv')
df.loc[2, "x"] = 345
df.loc[3, "x"] = 375
df

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I  345.0    NaN    NaN
3           3  mdb003      C  CIRC      B  375.0    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [70]:
df1 = df.dropna()
df1

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [71]:
X = df1[['x']].values.reshape(-1, 1)
y = df1['y'].values

print(X)
print(y)

[[535.]
 [433.]
 [488.]
 [544.]]
[475. 268. 145. 178.]


In [72]:
model_lr = linear_model.LinearRegression()
model_lr.fit(X, y)

LinearRegression()

In [73]:
X_ = df[df["y"].isnull()]["x"].values.reshape(-1,1)
y_ = model_lr.predict(X_)
print(X_)
print(y_)
df.loc[df["y"].isnull(), 'y'] = y_
df

[[345.]
 [375.]]
[171.81755196 190.14318707]


Unnamed: 0      id tissue class class2      x           y      r
0           0  mdb000      C  CIRC      N  535.0  475.000000  192.0
1           1  mdb001      A  CIRA      N  433.0  268.000000   58.0
2           2  mdb002      A  CIRA      I  345.0  171.817552    NaN
3           3  mdb003      C  CIRC      B  375.0  190.143187    NaN
4           4  mdb004      F  CIRF      I  488.0  145.000000   29.0
5           5  mdb005      F  CIRF      B  544.0  178.000000   26.0